### ISSUE TITLE
User Notification Not Working

### ISSUE THREAD

**Issue by Cyphers171** [oliviermaridat/plugin-rocketchat#3]
Good morning,

I'm trying to use rocketchat to notify users about taks assigned to them, but is not working even with user field set in integration to override the default channel in rocketchat. The override only works when set the user in integration project channel.

I'm using the plugin latest version.

**Comment by oliviermaridat** [comment]
Did you? 

> Project notification
> 
>     Copy and paste the webhook url into Integrations > RocketChat in the project settings
>     Add the channel name (Optional)
>     Enable RocketChat notification in the project
>     Enjoy!
> 

Also notice that in last Rocket.chat versions, you shall add the bot to the target channel : `/invite @rocket.cat` (I should probably add that to the doc)

**Comment by Cyphers171** [comment]
The process for projects with channel works perfectly, my problem is the user receive a direct message for the bot about a task assigned to the user, for example.
I enable notifications on projet and user, also configure the webhook in both integrations (projects and user).

**Comment by oliviermaridat** [comment]
Ah ok.

I checked the private notification on a Rocket.chat v0.x and v5.x and it is working perfectly.

I had to configure the webhook URL and Username (do not forget the "@") and to enable the notification on the "Notifications" view.

Maybe you need to first start a private discussion with @rocket.cat?

**Comment by Cyphers171** [comment]
I´m still not receiving  private message from rocket.cat. The configuration is as follow:

![rc1](https://user-images.githubusercontent.com/115110270/208168233-b4118ea6-062b-41ed-9d3f-e835086bb2ec.png)
![rc2](https://user-images.githubusercontent.com/115110270/208168239-87763533-2417-43e3-9a9e-0f1deb8447be.png)
![rc3](https://user-images.githubusercontent.com/115110270/208168243-08cb7d38-298b-4e86-a2e7-9e471852d73b.png)

My impression is that the username for the private message is not overriding the channel, and I tried to start a conversation with @rocket.cat, but no result. Somehow my version 2.2 of rocketchat has to do with it?

Kanborad - v1.2.22
RocketChat Plugin - 1.0.10
Rocket.Chat Application- 2.2.0
--



</body>
</html>

**Comment by Cyphers171** [comment]
My rockechat application was with a bug, and I have to make a redeploy to start working again. Notification is working. Thanks for the help, and sorry for the confusion. May close the issue.

**Comment by oliviermaridat** [comment]
Great!
